services:
  cuos-dev-container:
    image: "ghcr.io/cuos-dev/cuos-iac-dev-container:v0.2.1"
    x-digest: "sha256:17fd1e21133f266da11772a283eb2eae7ffe311e78a31659a41ee0bc5f222cb2"
    container_name: cuos-dev-container
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - type: bind
        source: /root/.docker/config.json
        target: /root/.docker/config.json
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        bind:
          create_host_path: false
      - type: bind
        source: /var/lib/containerd
        target: /var/lib/containerd
        bind:
          create_host_path: false
      - type: bind
        source: /var/run/cuos.sock
        target: /var/run/cuos.sock
        bind:
          create_host_path: false
      - type: bind
        source: /data
        target: /data
        bind:
          create_host_path: false
      - type: bind
        source: /dev
        target: /dev
        bind:
          create_host_path: false
      - type: bind
        source: /proc
        target: /proc
        bind:
          create_host_path: false
      - type: bind
        source: /etc/partition_mode
        target: /etc/partition_mode
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: "${SYSTEM_CONFIG_PATH:-/system.json}"
        target: /system.json
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /usr/local/share/ca-certificates/custom
        target: /usr/local/share/ca-certificates/custom
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /run/systemd/journal/socket
        target: /run/systemd/journal/socket
        bind:
          create_host_path: false
      - type: bind
        source: /var/log/journal
        target: /var/log/journal
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /etc/machine-id
        target: /etc/machine-id
        read_only: true
        bind:
          create_host_path: false
    environment:
      - TZ=Europe/Berlin
    restart: always
#    profiles:
#      - dev

