# SPDX-License-Identifier: Apache-2.0
services:
  cuos-iac-webui:
    image: "ghcr.io/cuos-dev/cuos-iac-webui:v0.3.4"
    x-digest: "sha256:ce9b7bec6d6625c38e5faae2f6dfe0847a20f20c5b104b16cc9091c5e6e14344"
    volumes:
      - type: bind
        source: "${SYSTEM_CONFIG_PATH:-/system.json}"
        target: /system.json
        read_only: true
        bind:
          create_host_path: false
      - type: volume
        source: iac-socket
        target: /socket
    ports:
      - "8030:3000"
    restart: always

volumes:
  iac-socket:
    name: "${IAC_SOCKET_VOLUME:-iac-socket}"
    external: true
