# SPDX-License-Identifier: Apache-2.0
services:
  cuos-iac-webui:
    image: "ghcr.io/cuos-dev/cuos-iac-webui:v0.4.0"
    x-digest: "sha256:db75b36efecd1f0a90303d52ed9979f25be06a19d7259430b3fb16eec5754fe0"
    volumes:
      - type: bind
        source: "${SYSTEM_CONFIG_PATH:-/system.json}"
        target: /system.json
        read_only: true
        bind:
          create_host_path: false
      - type: volume
        source: iac-socket
        target: /socket
    ports:
      - "8030:3000"
    restart: always

volumes:
  iac-socket:
    name: "${IAC_SOCKET_VOLUME:-iac-socket}"
    external: true
