services:
  cuos-iac:
    image: "ghcr.io/cuos-dev/cuos-iac:v0.2.1"
    x-digest: "sha256:d2ab19133b126a6fdfea6d9714676f964147c7afdae12ed657058e1ad937b04e"
    container_name: cuos-iac
    volumes:
      - type: bind
        source: "${HOME:-/root}/.docker/config.json"
        target: /root/.docker/config.json
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
      - type: bind
        source: "${SYSTEM_CONFIG_PATH:-./system.json}"
        target: /system.json
        bind:
          create_host_path: false
      - type: volume
        source: iac-socket
        target: /socket
    environment:
      SYSTEM_TYPE: "local"
      SYSTEM_CONFIG_PATH: "${SYSTEM_CONFIG_PATH:-${PWD}/system.json}"
      IAC_COMPOSE_PROJECT_NAME: "${IAC_COMPOSE_PROJECT_NAME:-iac-local}"
      IAC_LOCAL_SELFUPDATE: "${IAC_LOCAL_SELFUPDATE:-true}"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 500M
          pids: 100
        reservations:
          cpus: '0.5'
          memory: 250M
    read_only: true
    restart: always

volumes:
  iac-socket:
    name: "iac-socket"
    external: true
