services:
  cuos-iac:
    image: "ghcr.io/cuos-dev/cuos-iac:v0.3.0"
    x-digest: "sha256:0de81920b92bdc02e099e64751c5e5be08c47cee36fd4d3f0efb2e85beffdf99"
    volumes:
      - type: bind
        source: "${DOCKER_CONFIG:-${HOME:-/root}/.docker}/config.json"
        target: /root/.docker/config.json
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: false
      - type: bind
        source: "${SYSTEM_CONFIG_PATH:-./system.json}"
        target: /system.json
        bind:
          create_host_path: false
      - type: volume
        source: iac-socket
        target: /socket
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 64M
      - type: tmpfs
        target: /etc/ssl/certs
        tmpfs:
          size: 16M
    environment:
      SYSTEM_TYPE: "local"
      SYSTEM_CONFIG_PATH: "${SYSTEM_CONFIG_PATH:-${PWD}/system.json}"
      IAC_COMPOSE_PROJECT_NAME: "${IAC_COMPOSE_PROJECT_NAME:-iac-local}"
      IAC_SOCKET_VOLUME: "${IAC_SOCKET_VOLUME:-iac-socket}"
      IAC_LOCAL_SELFUPDATE: "${IAC_LOCAL_SELFUPDATE:-true}"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 500M
          pids: 100
        reservations:
          cpus: '0.5'
          memory: 250M
    read_only: true
    restart: always

volumes:
  iac-socket:
    name: "${IAC_SOCKET_VOLUME:-iac-socket}"
