services:
  cuos-iac-fleet-agent:
    image: "ghcr.io/cuos-dev/cuos-iac-fleet-agent:v0.3.3"
    x-digest: "sha256:1063460c24746fd5c75e184a165430afdde1e817764173e0c2a5453a9acb807f"
    volumes:
      - type: bind
        source: "${SYSTEM_CONFIG_PATH:-/system.json}"
        target: /system.json
        read_only: true
        bind:
          create_host_path: false
      - type: volume
        source: iac-socket
        target: /socket
    restart: always

volumes:
  iac-socket:
    name: "${IAC_SOCKET_VOLUME:-iac-socket}"
    external: true
