# SPDX-License-Identifier: Apache-2.0
services:
  cuos-iac-fleet-agent:
    image: "ghcr.io/cuos-dev/cuos-iac-fleet-agent:v0.3.4"
    x-digest: "sha256:15953bd0dc70a3306438f42bbfe26187c5b5f4790235e3d6756e34a45483bc9d"
    volumes:
      - type: bind
        source: "${SYSTEM_CONFIG_PATH:-/system.json}"
        target: /system.json
        read_only: true
        bind:
          create_host_path: false
      - type: volume
        source: iac-socket
        target: /socket
    restart: always

volumes:
  iac-socket:
    name: "${IAC_SOCKET_VOLUME:-iac-socket}"
    external: true
