services:
  cuos-iac-fleet-agent:
    image: "ghcr.io/cuos-dev/cuos-iac-fleet-agent:v0.3.2"
    x-digest: "sha256:1a4139acaef415533a7cbdb155887c45b0f5f4d74996fbe703a93946431a714d"
    volumes:
      - type: bind
        source: "${SYSTEM_CONFIG_PATH:-/system.json}"
        target: /system.json
        read_only: true
        bind:
          create_host_path: false
      - type: volume
        source: iac-socket
        target: /socket
    restart: always

volumes:
  iac-socket:
    name: "${IAC_SOCKET_VOLUME:-iac-socket}"
    external: true
